1
found 0 extensions at level 5
computing representatives of Genus of
None
Signature:  (0, 1)
Genus symbol at 2:    [2^1]_7
computing representatives of Genus of
None
Signature:  (0, 1)
Genus symbol at 2:    [2^1]_7
computing representatives of Genus of
None
Signature:  (0, 1)
Genus symbol at 2:    [4^1]_7
Cp,fp: 1
Genus of
[-4]
Signature:  (0, 1)
Genus symbol at 2:    [4^1]_7
C1: 1 Genus symbol at 2:    1^4 [2^4 4^1]_1
computing representatives
Traceback (most recent call last):
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/src/bin/sage-eval", line 10, in <module>
    eval(compile(s,'<cmdline>','exec'))
  File "<cmdline>", line 1, in <module>
  File "<string>", line 315, in classify
  File "<string>", line 258, in classify_purely_ns_nextp
  File "<string>", line 711, in next_prime_power
  File "<string>", line 695, in next_prime_power
  File "<string>", line 495, in prime_order
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/sage/quadratic_forms/genera/genus.py", line 3401, in representatives
    Q = QuadraticForm(ZZ,e*self.representative())
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/sage/quadratic_forms/genera/genus.py", line 3287, in representative
    self._compute_representative()
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/sage/quadratic_forms/genera/genus.py", line 3245, in _compute_representative
    gp.read(SAGE_EXTCODE + "/pari/simon/qfsolve.gp")
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/sage/interfaces/interface.py", line 223, in read
    self.eval(self._read_in_file_command(filename))
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/sage/interfaces/expect.py", line 1381, in eval
    return '\n'.join([self._eval_line(L, allow_use_file=allow_use_file, **kwds)
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/sage/interfaces/expect.py", line 1381, in <listcomp>
    return '\n'.join([self._eval_line(L, allow_use_file=allow_use_file, **kwds)
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/sage/interfaces/gp.py", line 441, in _eval_line
    a = Expect._eval_line(self, line,
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/sage/interfaces/expect.py", line 947, in _eval_line
    self._start()
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/sage/interfaces/gp.py", line 241, in _start
    Expect._start(self, alt_message, block_during_init)
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/sage/interfaces/expect.py", line 492, in _start
    self._expect = SageSpawn(cmd,
  File "sage/interfaces/sagespawn.pyx", line 65, in sage.interfaces.sagespawn.SageSpawn.__init__ (build/cythonized/sage/interfaces/sagespawn.c:1984)
  File "sage/interfaces/sagespawn.pyx", line 66, in sage.interfaces.sagespawn.SageSpawn.__init__ (build/cythonized/sage/interfaces/sagespawn.c:1938)
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/pexpect/pty_spawn.py", line 205, in __init__
    self._spawn(command, args, preexec_fn, dimensions)
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/pexpect/pty_spawn.py", line 303, in _spawn
    self.ptyproc = self._spawnpty(self.args, env=self.env,
  File "sage/interfaces/sagespawn.pyx", line 82, in sage.interfaces.sagespawn.SageSpawn._spawnpty (build/cythonized/sage/interfaces/sagespawn.c:2175)
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/site-packages/ptyprocess/ptyprocess.py", line 220, in spawn
    pid, fd = pty.fork()
  File "/home/lehrstuhl/ag-brandhorst/brandhorst/sage/local/lib/python3.9/pty.py", line 98, in fork
    pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
