Fix Cython testsuite failure on 32-bit
From upstream commit: d92a718a26c9354fbf35f31a17de5c069865a447
See also: https://github.com/cython/cython/issues/1548

--- a/tests/run/cpdef_enums.pyx
+++ b/tests/run/cpdef_enums.pyx
@@ -93,4 +93,4 @@ def verify_resolution_GH1533():
     3
     """
     THREE = 100
-    return PyxEnum.THREE
+    return int(PyxEnum.THREE)
